
class Failed(RuntimeError):
    pass

class BranchFailed(RuntimeError):
    pass